---
update: true

arch_base_packages:
  - sudo
  - dhcpcd
  - netctl
  - networkmanager
  - openssh
  - pipewire
  - man-db
  - man-pages
  - wget
  - reflector
  - picom
  - virtualbox-guest-utils
  - xorg
  - xorg-drivers
  - xorg-fonts
  - xorg-xinit
  - xterm

arch_other_packages:
  - git
  - neovim
  - mpv
  - alacritty
  - firefox
  - ntfs-3g
  - fastfetch
  - btop
  - xclip
  - p7zip
  - mako

debian_base_packages:
  - xorg
  - virtualbox-guest-utils
  
debian_other_packages:
  - git
  - neovim
  - mpv
  - alacritty
  - firefox
  - ntfs-3g
  - fastfetch
  - btop
  - xclip
  - p7zip
  
sway_wm_packages:
  - sway
  - swaylock
  - swaybg
  - i3status
  - swayidle
  - foot
  - polkit
  - xorg-xwayland

cinnamon_de_packages:
  - cinnamon-desktop-environment